10 LET MSG$ = "BASIC"
20 PRINT "MSG$ =", MSG$
30 PRINT "LEN(MSG$) =", LEN(MSG$)
40 LET LEFT_TEST$ = LEFT$(MSG$, 3)
50 PRINT "LEFT_TEST$ =", LEFT_TEST$
60 PRINT "LEN(LEFT_TEST$) =", LEN(LEFT_TEST$)
70 END
